pipeline {
    agent any

    // Triggers block to poll SCM for changes (e.g., every 15 minutes)
    triggers {
        pollSCM('H/15 * * * *')
    }

    // Environment block for remote Selenium connection
    environment {
        SELENIUM_HOST = 'selenium'
        SELENIUM_PORT = '4444'
        SELENIUM_REMOTE_URL = "http://${SELENIUM_HOST}:${SELENIUM_PORT}/wd/hub"
        JEST_JUNIT_OUTPUT_DIR = 'test-results'
        JEST_JUNIT_OUTPUT_NAME = 'results.xml'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm ci'
            }
        }

        stage('Start Application') {
            steps {
                // Start the Express app in the background
                sh 'node src/app.js &'
            }
        }

        // UI Test Stage using Jest
        stage('UI Tests') {
            steps {
                // Run Jest using the jest-junit reporter
                sh 'npx jest tests/e2e/home.test.js --reporters=default --reporters=jest-junit'
            }
        }
    }

    // Post step for JUnit reporting and process cleanup
    post {
        always {
            // Publish JUnit XML results generated by jest-junit in Jenkins
            junit allowEmptyResults: true, testResults: 'test-results/*.xml'
            
            // Stop the running Express server after tests finish
            sh 'pkill -f "node src/app.js" || true'
        }
        success {
            echo 'UI Tests Passed Successfully!'
        }
        failure {
            echo 'UI Tests Failed.'
        }
    }
}